// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaManejoBar.Models;

#nullable disable

namespace SistemaManejoBar.Migrations
{
    [DbContext(typeof(BarraDbContext))]
    [Migration("20260615044731_AgregarCamposPersonalizadosUsuario")]
    partial class AgregarCamposPersonalizadosUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SistemaManejoBar.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SistemaManejoBar.Models.CategoriaCoctel", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCategoria");

                    b.HasKey("IdCategoria")
                        .HasName("PK__categori__8A3D240C8DCE5215");

                    b.HasIndex(new[] { "NombreCategoria" }, "UQ__categori__788BF0FA1773A1F2")
                        .IsUnique();

                    b.ToTable("categoriaCoctel", (string)null);
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Coctel", b =>
                {
                    b.Property<int>("IdCoctel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCoctel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoctel"));

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int>("IdCristaleria")
                        .HasColumnType("int")
                        .HasColumnName("idCristaleria");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("instrucciones");

                    b.Property<string>("NombreCoctel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCoctel");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("int")
                        .HasColumnName("precioVenta");

                    b.HasKey("IdCoctel")
                        .HasName("PK__coctel__490EE0B8AC7D8D3D");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdCristaleria");

                    b.HasIndex(new[] { "NombreCoctel" }, "UQ__coctel__119308C3376FCC7C")
                        .IsUnique();

                    b.ToTable("coctel", (string)null);
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Cristalerium", b =>
                {
                    b.Property<int>("IdCristaleria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCristaleria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCristaleria"));

                    b.Property<double>("CapacidadOz")
                        .HasColumnType("float")
                        .HasColumnName("capacidadOz");

                    b.Property<string>("NombreCristaleria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCristaleria");

                    b.HasKey("IdCristaleria")
                        .HasName("PK__cristale__80DCDE0C2E3D9921");

                    b.HasIndex(new[] { "NombreCristaleria" }, "UQ__cristale__4CC6C0C8C376C714")
                        .IsUnique();

                    b.ToTable("cristaleria", (string)null);
                });

            modelBuilder.Entity("SistemaManejoBar.Models.DetalleRecetum", b =>
                {
                    b.Property<int>("IdDetalleReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDetalleReceta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleReceta"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdCoctel")
                        .HasColumnType("int")
                        .HasColumnName("idCoctel");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int")
                        .HasColumnName("idIngrediente");

                    b.HasKey("IdDetalleReceta")
                        .HasName("PK__detalleR__7A7D8379DF2B628A");

                    b.HasIndex("IdCoctel");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("detalleReceta", (string)null);
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idIngrediente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngrediente"));

                    b.Property<int>("IdTipoIngrediente")
                        .HasColumnType("int")
                        .HasColumnName("idTipoIngrediente");

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreIngrediente");

                    b.Property<double>("Stock")
                        .HasColumnType("float")
                        .HasColumnName("stock");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("unidad");

                    b.HasKey("IdIngrediente")
                        .HasName("PK__ingredie__563C0D33A647086D");

                    b.HasIndex("IdTipoIngrediente");

                    b.HasIndex(new[] { "NombreIngrediente" }, "UQ__ingredie__92BF05284D116A0F")
                        .IsUnique();

                    b.ToTable("ingrediente", (string)null);
                });

            modelBuilder.Entity("SistemaManejoBar.Models.TipoIngrediente", b =>
                {
                    b.Property<int>("IdTipoIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoIngrediente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoIngrediente"));

                    b.Property<string>("NombreTipoIngrediente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreTipoIngrediente");

                    b.HasKey("IdTipoIngrediente")
                        .HasName("PK__tipoIngr__17766B0815E208DF");

                    b.HasIndex(new[] { "NombreTipoIngrediente" }, "UQ__tipoIngr__6D5D16D4B73CCDA2")
                        .IsUnique();

                    b.ToTable("tipoIngrediente", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SistemaManejoBar.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SistemaManejoBar.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaManejoBar.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SistemaManejoBar.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Coctel", b =>
                {
                    b.HasOne("SistemaManejoBar.Models.CategoriaCoctel", "IdCategoriaNavigation")
                        .WithMany("Coctels")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__coctel__idCatego__5812160E");

                    b.HasOne("SistemaManejoBar.Models.Cristalerium", "IdCristaleriaNavigation")
                        .WithMany("Coctels")
                        .HasForeignKey("IdCristaleria")
                        .IsRequired()
                        .HasConstraintName("FK__coctel__idCrista__59063A47");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdCristaleriaNavigation");
                });

            modelBuilder.Entity("SistemaManejoBar.Models.DetalleRecetum", b =>
                {
                    b.HasOne("SistemaManejoBar.Models.Coctel", "IdCoctelNavigation")
                        .WithMany("DetalleReceta")
                        .HasForeignKey("IdCoctel")
                        .IsRequired()
                        .HasConstraintName("FK__detalleRe__idCoc__5BE2A6F2");

                    b.HasOne("SistemaManejoBar.Models.Ingrediente", "IdIngredienteNavigation")
                        .WithMany("DetalleReceta")
                        .HasForeignKey("IdIngrediente")
                        .IsRequired()
                        .HasConstraintName("FK__detalleRe__idIng__5CD6CB2B");

                    b.Navigation("IdCoctelNavigation");

                    b.Navigation("IdIngredienteNavigation");
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Ingrediente", b =>
                {
                    b.HasOne("SistemaManejoBar.Models.TipoIngrediente", "IdTipoIngredienteNavigation")
                        .WithMany("Ingredientes")
                        .HasForeignKey("IdTipoIngrediente")
                        .IsRequired()
                        .HasConstraintName("FK__ingredien__idTip__5441852A");

                    b.Navigation("IdTipoIngredienteNavigation");
                });

            modelBuilder.Entity("SistemaManejoBar.Models.CategoriaCoctel", b =>
                {
                    b.Navigation("Coctels");
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Coctel", b =>
                {
                    b.Navigation("DetalleReceta");
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Cristalerium", b =>
                {
                    b.Navigation("Coctels");
                });

            modelBuilder.Entity("SistemaManejoBar.Models.Ingrediente", b =>
                {
                    b.Navigation("DetalleReceta");
                });

            modelBuilder.Entity("SistemaManejoBar.Models.TipoIngrediente", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
